// Generates src/model/data/relations-matrix.ts from Archi's relationships.xml
// (com.archimatetool.model/model/relationships.xml, ArchiMate 3.2).
// Letter key (relationships-keys.xml): a=Access c=Composition f=Flow g=Aggregation
// i=Assignment n=Influence o=Association r=Realization s=Specialization t=Triggering v=Serving
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const xml = readFileSync(join(here, 'data', 'relationships.xml'), 'utf8');

const matrix = {};
let current = null;
for (const line of xml.split('\n')) {
  const src = line.match(/<source concept="([A-Za-z]+)"/);
  if (src) {
    current = {};
    matrix[src[1]] = current;
    continue;
  }
  const tgt = line.match(/<target concept="([A-Za-z]+)" relations="([a-z]*)"/);
  if (tgt && current) {
    current[tgt[1]] = tgt[2];
  }
}

const sources = Object.keys(matrix);
if (sources.length === 0) throw new Error('parsed nothing');

let out = `// GENERATED by tools/generate-rules.mjs from Archi's relationships.xml (ArchiMate 3.2).
// Do not edit by hand. Letter key: a=Access c=Composition f=Flow g=Aggregation
// i=Assignment n=Influence o=Association r=Realization s=Specialization t=Triggering v=Serving
export const relationsMatrix: Record<string, Record<string, string>> = {
`;
for (const s of sources) {
  out += `  ${s}: {\n`;
  for (const [t, rels] of Object.entries(matrix[s])) {
    out += `    ${t}: '${rels}',\n`;
  }
  out += '  },\n';
}
out += '};\n';

const dest = join(here, '..', 'src', 'model', 'data');
mkdirSync(dest, { recursive: true });
writeFileSync(join(dest, 'relations-matrix.ts'), out);
console.log(`wrote relations-matrix.ts: ${sources.length} source concepts`);
